version: '3.8'

services:
  backendg:
    restart: unless-stopped
    image: gvilliger/backend223
    container_name: backendg
    ports:
      - 8080:8080
    depends_on:
      - dbg
  frontendg:
    restart: unless-stopped
    image: gvilliger/frontend223
    container_name: frontendg
    depends_on:
      - backendg
    ports:
      - 8907:80

  dbg:
    restart: unless-stopped
    image: 'postgres:16'
    container_name: dbg
    ports:
      - '5432:5431'
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'postgres'






